name: build

on:
  push:
    branches: [ main, actions ]
    paths: ['general-knotconverter/**', '.github/workflows/**']
  pull_request:
    branches: [ main, actions ]
    paths: ['general-knotconverter/**', '.github/workflows/**']
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd general-knotconverter
          cargo build --release

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: test-${{ matrix.os }}
          path: |
            target/release/general-knotconverter
            target/release/general-knotconverter.exe
